id,Title,Description
1,Free Verse,"<p>A free verse is a type of poem that does not follow a specific meter or a specific rhyme scheme. There is no fixed form. A free verse poem does not have a specific rhyme pattern that it needs to follow and there are no set rules to writing a poem in free verse. The poem has natural pauses based on phrases. A person will pause in this poem like they would if they are speaking to another.
his type of poem is also known as a vers libre. Those are the French words for free verse. There is no set length requirement for a free verse poem either. Free verse is used mostly in contemporary poetry.

Free verse allows a person to express themselves through the words they are writing and not through specific meters. This will allow a person the freedom they need to chose which words to use and will focus on expressing their thoughts to the audience.</p>"
2,Rhyme,"A rhyme poem is a form of poetry has the repetition of the same or similar sounds of two or more words, often at the end of the line"
3,Haiku,"Haiku poems are a short form of Japanese poetry consisting of nature-related and vibrant imagery. It is typically written with three lines and 17 syllables (5-7-5 syllable count) in English. However, in Japan they do not use syllable counts, rather sounds. So, haikus do not need to adhere to this traditional English structure."
4,Lyric,Lyric Poetry is a type of poem in which the poetic expression is much more personal and tends to show more feeling or emotion from the poet throughout the piece but in a musical way.
5,Senryu,"A Senryu is a type of poem that paints a mental image with a short amount of words and a set amount of syllables per line. The senryu poem originates from Japan and is very similar to a Haiku poem. Both haikus and senryus have rules regarding how many syllables the author can use and how many syllables must be used on each of the three lines.

Typically, both haikus and senryus are made up of seventeen syllables written onto three lines. The first line of the poem must contain five syllables, the second line has seven syllables and the third line has five syllables"
6,Limerick,"Limericks are a fun form of poetic expression that have a five-line A-A-B-B-A rhyme scheme. The first, second, and fifth lines have a strong downbeat and rhyme. Lines three and four have five to seven (two metrical feet) syllables and also rhyme with each other. Limerick poems have an anapestic trimester, three metrical feet with two unstressed syllables followed by a stressed syllable.

Most of the limerick poems have a humorous or amusingly coarse or irreverent subject, and the first four lines set up the joke, and the last line delivers the punchline."
7,Quatrain,"A Quatrain is a type of poem which has its lines of verse grouped in four-line stanzas. It is one of the most common stanza forms in English verse, and can be traced back to the ancient literary traditions of Rome, Greece and China. The term quatrain may refer to a single stanza or the entire poem.

There are many forms of quatrain, each featuring variations of line length and rhyme schemes. Some recurring forms have become accepted as conventions and given names."
8,Sijo,"A Sijo is a type of poem that has three lines containing fourteen to sixteen lines each. The Sijo is a poem of Korean descent where each line of the poem having its own role. The first line is used in order to introduce the theme or topic of the poem. In the second line is meant to delve deeper, give more information about the theme that was introduced in the first line. It's meant to change or agree with and give detail on what the poem is about. The last line of a Sijo poem is the conclusion line. It takes the information from the second line about the topic from the first line and ends it in a way that is both beautiful and satisfying, or challenging depending on the poet. The ending line is not meant to be predictable, in fact, it's meant to twist what you know so that it is unexpected and enjoyable. A Sijo was originally meant to be sung so each line should have its own natural break. 

Sijo is the classic form of unrhymed poetry in Korea. Sijo have three long lines. Each line varies between 14 and 16 syllables, with the middle line often the longest. The first line states a theme, the second line counters it, and the third line resolves the poem."
9,Sonnet,"<p>A Sonnet is a type of poem in which the structure is very specific, following a clear rhyme scheme that flowed through fourteen lines. There have been many different forms of the sonnet, generally speaking, throughout the centuries passed; However, many ""sonneteers"" (as they are often known) claim that the basis of a sonnet in poetry has indeed evolved throughout this time. The word 'sonnet' is derivative from the Italian word 'sonnetto', which loosely translates into many different meanings, specifically a little poem, song, or sound. The sonnet was also created in Italy by Giacomo da Lentini, who headed the Sicilian School in Tuscany in the late 1200s. Back during that time period, many of the sonnets that were written were meant to portray the means of an argument; However, as time has gone on, we have seen the structural aspects of sonnets, as well as themes, take varying turns and changes. Sonnets have been written and published all throughout the world -- By the English, Russians, Dutch, Germans, to name a few -- and continue to be popular still today in the 21st century. Sonnets are Lyric poems that are 14 lines and usually have one or more conventional rhyme schemes. </p>"
11,Abecederian,"<p><span class=""ql-font-Poppins"">This is a form of poetry where each line starts with the successive letter of the alphabet</span></p><p><br></p><p class=""ql-align-center""><strong class=""ql-font-Poppins""><u>Example</u></strong></p><p class=""ql-align-center"">A bird calls, </p><p class=""ql-align-center"">Butterflies dance,</p><p class=""ql-align-center"">Clouds drift slowly...</p>"
